# Site settings
title: Rise Vision Documentation
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://help.risevision.com" # the base hostname & protocol for your site
metaImageUrl: "https://s3.amazonaws.com/Store-Products/Meta"
twitter_username: risevision
github_username:  RiseVision
hashTag: "#"
html5mode: "false"

# Build settings
markdown: redcarpet

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

kramdown:
  # use Github Flavored Markdown
  input: GFM

highlighter: pygments

exclude:
  - bower.json
  - node_modules
  - gulpfile.js
  - package.json
  - Gemfile
  - Gemfile.lock
  - risevision-documentation.iml
  - cname-config
  - karma.conf.js
  - tests


# Default categories (in order) to appear in the navigation
developerSections: [
	['developer/getting-started', 'Getting Started', [
      ['developer/getting-started/registration', 'Registration']
    ]],
    ['developer/core-api', 'Core API', [
      ['developer/core-api/companies', 'Companies'],
      ['developer/core-api/displays', 'Displays'],
      ['developer/core-api/users', 'Users'],
      ['developer/core-api/countries', 'Countries'],
      ['developer/core-api/presentations', 'Presentations'],
      ['developer/core-api/schedules', 'Schedules'],
      ['developer/core-api/systemmessages', 'System Messages']
    ]],
    ['developer/content-api', 'Content API', [
      ['developer/content-api/presentations', 'Presentations']
    ]],
    ['developer/viewer-api', 'Viewer API', [
      ['developer/viewer-api/content', 'Content'],
      ['developer/viewer-api/notifications', 'Notifications']
    ]],
    ['developer/player-api', 'Player API', [
      ['developer/player-api/cache', 'Cache'],
      ['developer/player-api/installer', 'Installer'],
      ['developer/player-api/player', 'Player'],
      ['developer/player-api/viewer', 'Viewer']
    ]],
    ['developer/store-api', 'Store API'],
    ['developer/storage-api', 'Storage Api'],
    ['developer/presentations', 'Presentations', [
      ['developer/presentations/multi-page', 'Multi-Page Presentations'],
      ['developer/presentations/presentation-tutorials', 'Presentation Tutorials']
    ]],
    ['developer/widget-api', 'Widgets'],
    ['developer/common-header', 'Common Header']
]

userSections: [
    ['user/getting-started', 'Getting Started'],
    ['user/company', 'Company'],
    ['user/presentation', 'Presentation'],
    ['user/content', 'Content'],
    ['user/display', 'Display'],
    ['user/schedule', 'Schedule'],
    ['user/player', 'Player',[
      ['user/player/chrome-app','Chrome App Player']
    ]],
    ['user/users', 'Users'],
    ['user/storage', 'Storage'],
    ['user/alerts', 'Alerts'],
]


# Dates are not included in permalinks
permalink: /:categories/:title

gems:
  - jekyll-sitemap
  - jekyll_github_sample
  - jekyll-lunr-js-search
