# Site settings
title: Rise Vision Documentation
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rise-vision.github.io" # the base hostname & protocol for your site
twitter_username: risevision
github_username:  RiseVision

# Build settings
markdown: redcarpet

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

kramdown:
  # use Github Flavored Markdown
  input: GFM

highlighter: pygments

exclude:
  - bower.json
  - node_modules
  - gulpfile.js
  - package.json
  - Gemfile
  - Gemfile.lock
  - risevision-documentation.iml


# Default categories (in order) to appear in the navigation
sections: [
    ['documentation/core-api', 'Core API'],
    ['documentation/viewer-api', 'Viewer API'],
    ['documentation/player-api', 'Player API'],
    ['documentation/widget-api', 'Widget API'],
    ['documentation/store-api', 'Store API'],
    ['documentation/storage-api', 'Storage Api'],
    ['ref', 'Reference'],
    ['dev', 'Developers'],
    ['post', 'Posts']
]

# Dates are not included in permalinks
permalink: none

gems:
  - jekyll-sitemap
  - jekyll_github_sample
  - jekyll-lunr-js-search