# Site settings
title: Rise Vision Documentation
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rise-vision.github.io" # the base hostname & protocol for your site
twitter_username: risevision
github_username:  RiseVision
hashTag: "#"
html5mode: "false"

# Build settings
markdown: redcarpet

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

kramdown:
  # use Github Flavored Markdown
  input: GFM

highlighter: pygments

exclude:
  - bower.json
  - node_modules
  - gulpfile.js
  - package.json
  - Gemfile
  - Gemfile.lock
  - risevision-documentation.iml
  - cname-config
  - karma.conf.js
  - tests


# Default categories (in order) to appear in the navigation
developerSections: [
    ['developer/core-api', 'Core API', [
      ['developer/core-api/companies', 'Companies'],
      ['developer/core-api/displays', 'Displays'],
      ['developer/core-api/users', 'Users'],
      ['developer/core-api/countries', 'Countries'],
      ['developer/core-api/presentations', 'Presentations'],
      ['developer/core-api/schedules', 'Schedules'],
      ['developer/core-api/systemmessages', 'System Messages']
    ]],
    ['developer/viewer-api', 'Viewer API', [
      ['developer/viewer-api/content', 'Content'],
      ['developer/viewer-api/notifications', 'Notifications']
    ]],
    ['developer/player-api', 'Player API', [
      ['developer/player-api/cache', 'Cache'],
      ['developer/player-api/installer', 'Installer'],
      ['developer/player-api/player', 'Player'],
      ['developer/player-api/viewer', 'Viewer']
    ]],
    ['developer/widget-api', 'Widget API', [
      ['developer/widget-api/widget', 'Widget']
    ]],
    ['developer/store-api', 'Store API', [
      ['developer/store-api/store', 'Store']
    ]],
    ['developer/storage-api', 'Storage Api', [
      ['developer/storage-api/storage', 'Storage']
    ]],
    ['developer/common-header', 'Common Header', [
      ['developer/common-header/usage', 'Usage']
    ]],
    ['ref', 'Reference'],
    ['dev', 'Developers'],
    ['post', 'Posts']
]

userSections: [
    ['user/getting-started', 'Getting Started'],
    ['user/company', 'Company', [
      ['user/company/management', 'Company Management'],
    ]],
    ['user/presentation', 'Presentation', [
      ['user/presentation/management', 'Presentation Management'],
    ]],
    ['user/content', 'Content'],
    ['user/display', 'Display', [
      ['user/display/management', 'Display Management'],
    ]],
    ['user/user', 'User'],
    ['user/schedule', 'Schedule', [
       ['user/schedule/management', 'Schedule Management'],
    ]],
    ['user/player', 'Player'],
    ['user/users', 'Users', [
      ['user/users/management', 'User Management'],
    ]],
    ['user/storage', 'Storage', [
      ['user/storage/management', 'Storage Management'],
    ]],
    ['user/alerts', 'Alerts'],
]


# Dates are not included in permalinks
permalink: none

gems:
  - jekyll-sitemap
  - jekyll_github_sample
  - jekyll-lunr-js-search
