# Site settings
title: Rise Vision Documentation
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://help.risevision.com" # the base hostname & protocol for your site
metaImageUrl: "https://s3.amazonaws.com/Store-Products/Meta"
faviconUrl: "http://s3.amazonaws.com/Rise-Images/favicons"
twitter_username: risevision
github_username:  RiseVision
hashTag: ""
html5mode: "true"
basehref: "/"

# Build settings
markdown: redcarpet

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

kramdown:
  # use Github Flavored Markdown
  input: GFM

highlighter: pygments

exclude:
  - bower.json
  - node_modules
  - gulpfile.js
  - package.json
  - Gemfile
  - Gemfile.lock
  - risevision-documentation.iml
  - cname-config
  - test
  - reports
  - vendor
  - circle.yml


# Default categories (in order) to appear in the navigation
developerSections: [
	['developer/getting-started', 'Getting Started', [
      ['developer/getting-started/registration', 'Registration']
    ]],
    ['developer/core-api', 'Core API', [
      ['developer/core-api/company', 'Company'],
      ['developer/core-api/display', 'Display'],
      ['developer/core-api/user', 'User'],
      ['developer/core-api/country', 'Country'],
      ['developer/core-api/timezone', 'Timezone'],
      ['developer/core-api/presentation', 'Presentation'],
      ['developer/core-api/schedule', 'Schedule'],
      ['developer/core-api/systemmessage', 'System Message']
    ]],
    ['developer/content-api', 'Content API', [
      ['developer/content-api/presentations', 'Presentations']
    ]],
    ['developer/viewer-api', 'Viewer API', [
      ['developer/viewer-api/content', 'Content'],
      ['developer/viewer-api/notifications', 'Notifications']
    ]],
    ['developer/player-api', 'Player API', [
      ['developer/player-api/cache', 'Cache'],
      ['developer/player-api/installer', 'Installer'],
      ['developer/player-api/player', 'Player'],
      ['developer/player-api/viewer', 'Viewer']
    ]],
    ['developer/store-api', 'Store API',[
      ['developer/store-api/store-auth', 'Store Authorization'],
      ['developer/store-api/subscription-status', 'Subscription Status']
    ]],
    ['developer/storage-api', 'Storage API'],
    ['developer/presentations', 'Presentations', [
      ['developer/presentations/multi-page', 'Multi-Page Presentations'],
      ['developer/presentations/presentation-tutorials', 'Presentation Tutorials']
    ]],
    ['developer/widget-api', 'Widgets'],
    ['developer/web-components', 'Web Components'],
    ['developer/common-header', 'Common Header']
]

userSections: [
    ['user/getting-started', 'Getting Started'],
    ['user/alerts', 'Alerts'],
    ['user/company', 'Company'],
    ['user/content', 'Content'],
    ['user/display', 'Display'],
    ['user/player', 'Player',[
      ['user/player/chrome-app','Chrome App Player']
      ['user/player/native-player','Native Player']
    ]],
    ['user/presentation', 'Presentation'],
    ['user/schedule', 'Schedule'],
    ['user/storage', 'Storage',[
      ['user/storage/tagging','Tagging']
    ]],
    ['user/store', 'Store'],
    ['user/users', 'Users'],
]


# Dates are not included in permalinks
permalink: /:categories/:title
relative_permalinks: true

gems:
  - jekyll-sitemap
  - jekyll_github_sample
  - jekyll-lunr-js-search
